### ISSUE TITLE
Strange: "Abort trap: 6" output

### ISSUE THREAD

**Issue by karstenlitsche** [jensmeder/Phoenx#25]
Using phoenix version 0.2.3
When creating my project I get:
> Generating project Test.xcodeproj
> Abort trap: 6

The generated Xcode project seems ok.
[Test.pxproject](https://github.com/jensmeder/Phoenx/files/721934/Test.pxproject.txt)

**Comment by simonseyer** [comment]
Maybe on of this PRs can solve your problem: #23 or #28

**Comment by simonseyer** [comment]
Please retest with `0.2.4`. Thanks @karstenlitsche

**Comment by karstenlitsche** [comment]
0.2.4 fixed the issue. 👍
