### ISSUE TITLE
Improve naming of copy buid phase

### ISSUE THREAD

**Issue by simonseyer** [jensmeder/Phoenx#9]
Currently the build phase to copy the frameworks is just called `Copy Files`, `Embed Frameworks` would be a more suitable name.

Probably has to be done here: https://github.com/jensmeder/Phoenx/blob/9d2757a94821b781d30af13915d3d3c60e174a49/lib/phoenx/use_cases/generate_target.rb#L437

**Comment by jensmeder** [comment]
Included in release [0.2.1](https://github.com/jensmeder/Phoenx/releases/tag/0.2.1)
